###############################################################################
#   @author       :   ArveVM 
#   @date         :   15.march.2022
#   @integration  :   Uptime
#   @description  :   track uptime of HA
#   @basic concept: 
#     The uptime sensor stores the timestamp (date and time) 
#     when Home Assistant was last started.
#     (while system_monitor provides last reboot of host)
#     
#   further info: https://www.home-assistant.io/integrations/uptime/
#
###############################################################################


sensor:
  - platform: uptime
    name: HA Last reboot