# ArveVM: create toDo - tasks in other packages,, this package summarize the number of
#         active toDo-tasks,, and create option to a chip/button/card to show that there
#         are in fact tasks that need dooing  ;)

homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        solution: "toDo"

    # tag package specific entities with package name
    sensor.todo_counter:
      <<: *customize

template:
  - sensor:
      - name: "toDo Counter"
        unique_id: sensor.todo_counter
        icon: mdi:list-status
        state: >-
          {{ states.input_boolean
            |selectattr('entity_id', 'search', '_todo$')
            |selectattr('state', 'eq', 'on') | list | count }}
